### ISSUE TITLE
Invalid type specified "Int"

### ISSUE THREAD

**Issue by mariebosq** [assemblee-virtuelle/science-tour#25]
Quand on clic sur l'onglet Défis on tombe sur cette erreur : 

`Uncaught PHP Exception InvalidArgumentException: "Invalid type specified "Int"." at /var/www/html/st-marie/science-tour/vendor/doctrine/mongodb-odm/lib/Doctrine/ODM/MongoDB/Types/Type.php line 148`

**Comment by Septentrion** [comment]
Il semblerait que ce soit juste une erreur de typographie :

```@MongoDB\Field(type="Int")```

> remplacer **Int** par **int** (ou **integer**)

**Comment by mariebosq** [comment]
Il suffisait de le mettre en minuscule
